# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /nfs/store2.jinr.ru/user/v/vtokareva/parallel_pwa/PWnAge

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /nfs/store2.jinr.ru/user/v/vtokareva/parallel_pwa/PWnAge

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /nfs/store2.jinr.ru/user/v/vtokareva/parallel_pwa/PWnAge/CMakeFiles /nfs/store2.jinr.ru/user/v/vtokareva/parallel_pwa/PWnAge/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /nfs/store2.jinr.ru/user/v/vtokareva/parallel_pwa/PWnAge/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named PWnAge

# Build rule for target.
PWnAge: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 PWnAge
.PHONY : PWnAge

# fast build rule for target.
PWnAge/fast:
	$(MAKE) -f CMakeFiles/PWnAge.dir/build.make CMakeFiles/PWnAge.dir/build
.PHONY : PWnAge/fast

src/TCache.o: src/TCache.cpp.o
.PHONY : src/TCache.o

# target to build an object file
src/TCache.cpp.o:
	$(MAKE) -f CMakeFiles/PWnAge.dir/build.make CMakeFiles/PWnAge.dir/src/TCache.cpp.o
.PHONY : src/TCache.cpp.o

src/TCache.i: src/TCache.cpp.i
.PHONY : src/TCache.i

# target to preprocess a source file
src/TCache.cpp.i:
	$(MAKE) -f CMakeFiles/PWnAge.dir/build.make CMakeFiles/PWnAge.dir/src/TCache.cpp.i
.PHONY : src/TCache.cpp.i

src/TCache.s: src/TCache.cpp.s
.PHONY : src/TCache.s

# target to generate assembly for a file
src/TCache.cpp.s:
	$(MAKE) -f CMakeFiles/PWnAge.dir/build.make CMakeFiles/PWnAge.dir/src/TCache.cpp.s
.PHONY : src/TCache.cpp.s

src/TJpsiToKKpi0Const.o: src/TJpsiToKKpi0Const.cpp.o
.PHONY : src/TJpsiToKKpi0Const.o

# target to build an object file
src/TJpsiToKKpi0Const.cpp.o:
	$(MAKE) -f CMakeFiles/PWnAge.dir/build.make CMakeFiles/PWnAge.dir/src/TJpsiToKKpi0Const.cpp.o
.PHONY : src/TJpsiToKKpi0Const.cpp.o

src/TJpsiToKKpi0Const.i: src/TJpsiToKKpi0Const.cpp.i
.PHONY : src/TJpsiToKKpi0Const.i

# target to preprocess a source file
src/TJpsiToKKpi0Const.cpp.i:
	$(MAKE) -f CMakeFiles/PWnAge.dir/build.make CMakeFiles/PWnAge.dir/src/TJpsiToKKpi0Const.cpp.i
.PHONY : src/TJpsiToKKpi0Const.cpp.i

src/TJpsiToKKpi0Const.s: src/TJpsiToKKpi0Const.cpp.s
.PHONY : src/TJpsiToKKpi0Const.s

# target to generate assembly for a file
src/TJpsiToKKpi0Const.cpp.s:
	$(MAKE) -f CMakeFiles/PWnAge.dir/build.make CMakeFiles/PWnAge.dir/src/TJpsiToKKpi0Const.cpp.s
.PHONY : src/TJpsiToKKpi0Const.cpp.s

src/test_JpsiToKKpi0.o: src/test_JpsiToKKpi0.cpp.o
.PHONY : src/test_JpsiToKKpi0.o

# target to build an object file
src/test_JpsiToKKpi0.cpp.o:
	$(MAKE) -f CMakeFiles/PWnAge.dir/build.make CMakeFiles/PWnAge.dir/src/test_JpsiToKKpi0.cpp.o
.PHONY : src/test_JpsiToKKpi0.cpp.o

src/test_JpsiToKKpi0.i: src/test_JpsiToKKpi0.cpp.i
.PHONY : src/test_JpsiToKKpi0.i

# target to preprocess a source file
src/test_JpsiToKKpi0.cpp.i:
	$(MAKE) -f CMakeFiles/PWnAge.dir/build.make CMakeFiles/PWnAge.dir/src/test_JpsiToKKpi0.cpp.i
.PHONY : src/test_JpsiToKKpi0.cpp.i

src/test_JpsiToKKpi0.s: src/test_JpsiToKKpi0.cpp.s
.PHONY : src/test_JpsiToKKpi0.s

# target to generate assembly for a file
src/test_JpsiToKKpi0.cpp.s:
	$(MAKE) -f CMakeFiles/PWnAge.dir/build.make CMakeFiles/PWnAge.dir/src/test_JpsiToKKpi0.cpp.s
.PHONY : src/test_JpsiToKKpi0.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... PWnAge"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... src/TCache.o"
	@echo "... src/TCache.i"
	@echo "... src/TCache.s"
	@echo "... src/TJpsiToKKpi0Const.o"
	@echo "... src/TJpsiToKKpi0Const.i"
	@echo "... src/TJpsiToKKpi0Const.s"
	@echo "... src/test_JpsiToKKpi0.o"
	@echo "... src/test_JpsiToKKpi0.i"
	@echo "... src/test_JpsiToKKpi0.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

